In [1]:
from stretch_body.robot import Robot
import math
import time

In [2]:
robot = Robot()

In [3]:
robot.startup()

In [4]:
if not robot.is_calibrated():
    robot.home()

In [5]:
# robot.stow()

In [6]:
# robot.stop()

# Camera Transforms

In [7]:
import os
urdf_path = os.path.join(os.getenv("HELLO_FLEET_PATH"), os.getenv("HELLO_FLEET_ID"), "exported_urdf", "stretch.urdf")
mesh_path = os.path.join(os.getenv("HELLO_FLEET_PATH"), os.getenv("HELLO_FLEET_ID"), "exported_urdf")


from pytransform3d.urdf import UrdfTransformManager
import pytransform3d.transformations as pt
import pytransform3d.visualizer as pv
import numpy as np


tm = UrdfTransformManager()
with open(urdf_path, "r") as f:
    urdf = f.read()
    tm.load_urdf(urdf, mesh_path=mesh_path)

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [9]:
s = robot.get_status()
head_pan = s['head']['head_pan']['pos']
head_tilt = s['head']['head_tilt']['pos']
print('head_pan:', head_pan, 'head_tilt', head_tilt)


# Get Camera transform
tm.set_joint("joint_head_pan", head_pan)
tm.set_joint("joint_head_pan", head_pan)
camera_transform = tm.get_transform('base_link', 'camera_link')

print(camera_transform)

# use this transform in du.transform_pose (i.e. see get_current_pcd)

head_pan: 1.569262346007011 head_tilt -0.01227184630308513
[[ 0.00646493  0.99944347 -0.03272549 -0.01340795]
 [-0.01678736  0.03283003  0.99931996 -1.31305613]
 [ 0.99983818 -0.00591116  0.01699026 -0.00277494]
 [ 0.          0.          0.          1.        ]]


In [ ]:
# Visualize URDF using Open3D
fig = pv.figure()
fig.plot_graph(tm, "base_link", s=0.1, show_visuals=True)
fig.view_init()
fig.show()