In [1]:
import cv2
import numpy as np
import base64
from PIL import Image
from io import BytesIO


In [132]:
# Encode
def get_fake_rgbd(rgb=None, h=480, w=640):
    rgb = np.uint8(np.random.rand(h, w, 3) * 255) if rgb is None else rgb
    depth = np.random.randint(0, 2, (h, w))
    pts = np.random.randint(0, 5, (h * w, 3))
    return rgb, depth

rgb, depth = get_fake_rgbd()
rgb_bytes = rgb.tobytes()

# cv2 encoding
encode_param = [int(cv2.IMWRITE_WEBP_QUALITY), 10]
fmt = ".webp"
# _, rgb_bytes = cv2.imencode(fmt, cv2.cvtColor(rgb, cv2.COLOR_RGB2BGR))
# Note that including encode_param will fail the assert at the bottom, but is probably fine
_, rgb_bytes = cv2.imencode(fmt, cv2.cvtColor(rgb, cv2.COLOR_RGB2BGR), encode_param)

encoded_msg = base64.b64encode(rgb_bytes)
print(encoded_msg[:100])

921600
b'UklGRgRuAQBXRUJQVlA4IPhtAQDQSgKdASqAAuABB0CWJbACdO3FPHbRMI/cP2l///2//L4iv//J5+t///KG/W///Sv///U5/1P/'


In [135]:
# Decode
res = base64.b64decode(encoded_msg)
np_res = np.frombuffer(res, dtype=np.uint8)
# np_res = np.frombuffer(res, dtype=np.uint8).reshape(rgb.shape)

# cv2 decoding
np_res = cv2.imdecode(np_res, cv2.IMREAD_COLOR)
np_res = cv2.cvtColor(np_res, cv2.COLOR_BGR2RGB)

print(np_res.shape)

error: OpenCV(4.5.2) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - dst is not a numpy array, neither a scalar
>  - Expected Ptr<cv::UMat> for argument 'dst'


In [134]:
print(type(rgb))
print(type(np_res))
print(np_res.shape, rgb.shape)

print(rgb[0])
print(np_res[0])

print(np.array_equal(rgb, np_res))

# im = Image.open(BytesIO(npres))
# im = Image.open(res)


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
(480, 640, 3) (480, 640, 3)
[[138  17 119]
 [  0   9 194]
 [115  13  25]
 ...
 [201  50  54]
 [117 207  28]
 [218 211   1]]
[[ 44  22 141]
 [ 30  35 131]
 [  0  57 105]
 ...
 [140  65  93]
 [160 172 154]
 [154 210 170]]
False
